/**
 * Privacy Notice Component
 *
 * Simple privacy notice for academic research tool
 * GDPR/CCPA compliant disclosure
 */

import React from 'react';
import {
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  Button,
  Typography,
  Box,
  Divider,
} from '@mui/material';

interface Props {
  open: boolean;
  onClose: () => void;
}

const PrivacyNotice: React.FC<Props> = ({ open, onClose }) => {
  return (
    <Dialog
      open={open}
      onClose={onClose}
      maxWidth="md"
      fullWidth
      aria-labelledby="privacy-dialog-title"
    >
      <DialogTitle id="privacy-dialog-title">
        Privacy & Data Usage
      </DialogTitle>
      <DialogContent dividers>
        <Typography variant="h6" gutterBottom>
          Data Collection
        </Typography>
        <Typography variant="body2" paragraph>
          PhonoLex does not collect, store, or transmit any personal information. All queries are processed
          in real-time and not logged or retained beyond the duration of your session.
        </Typography>

        <Divider sx={{ my: 2 }} />

        <Typography variant="h6" gutterBottom>
          Session Data
        </Typography>
        <Typography variant="body2" paragraph>
          Your browser may store minimal session data (e.g., theme preference) using local storage.
          This data never leaves your device and can be cleared at any time through your browser settings.
        </Typography>

        <Divider sx={{ my: 2 }} />

        <Typography variant="h6" gutterBottom>
          Third-Party Services
        </Typography>
        <Typography variant="body2" paragraph>
          PhonoLex does not use analytics, tracking cookies, or third-party advertising services.
          All phonological data is processed locally by the PhonoLex server without external API calls.
        </Typography>

        <Divider sx={{ my: 2 }} />

        <Typography variant="h6" gutterBottom>
          Research & Clinical Use
        </Typography>
        <Typography variant="body2" paragraph>
          PhonoLex is designed for research and clinical applications by speech-language pathologists
          and linguists. Word lists and phonological analyses generated by this tool should be validated
          by qualified professionals before clinical use.
        </Typography>

        <Divider sx={{ my: 2 }} />

        <Typography variant="h6" gutterBottom>
          Accessibility
        </Typography>
        <Typography variant="body2" paragraph>
          PhonoLex is committed to WCAG 2.1 AA accessibility standards. If you encounter any barriers
          using this application, please report them via our GitHub repository.
        </Typography>

        <Box sx={{ mt: 3, p: 2, bgcolor: 'action.hover', borderRadius: 1 }}>
          <Typography variant="caption" color="text.secondary">
            Last Updated: 2025-10-28 | Version 2.0
          </Typography>
        </Box>
      </DialogContent>
      <DialogActions>
        <Button onClick={onClose} variant="contained" autoFocus>
          Close
        </Button>
      </DialogActions>
    </Dialog>
  );
};

export default PrivacyNotice;
